# Generated by Django 5.1.2 on 2024-11-08 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('photo', models.FileField(max_length=255, upload_to='egitmen/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='EgitimPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('13', '13'), ('14', '14'), ('15', '15'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=2, verbose_name='Training Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.egitmen', verbose_name='Teacher')),
            ],
        ),
    ]
