# Generated by Django 5.1.2 on 2024-11-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egitimplan',
            name='egitmen',
        ),
        migrations.RemoveField(
            model_name='egitimplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Egitmen',
        ),
        migrations.DeleteModel(
            name='EgitimPlan',
        ),
    ]
