# Generated by Django 5.1.2 on 2024-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branch',
            field=models.PositiveIntegerField(default=0, verbose_name='Branch'),
        ),
    ]
