# Generated by Django 5.1.2 on 2024-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='kvkk_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='terms_read',
            field=models.BooleanField(default=True),
        ),
    ]
