# Generated by Django 5.1.2 on 2024-10-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_employee_kvkk_read_alter_employee_terms_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
