# Generated by Django 5.1.2 on 2024-11-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_customuser_gender'),
        ('files', '0002_remove_activitycost_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('location', models.ManyToManyField(to='company.city', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Activitysupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('location', models.ManyToManyField(to='company.city', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Activitycost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.activity', verbose_name='Activite')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.activitysupplier', verbose_name='Aktivite Tedarikçisi')),
            ],
        ),
        migrations.CreateModel(
            name='Buyercompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('short_name', models.CharField(max_length=5, unique=True, verbose_name='Kısa adı')),
                ('contact', models.CharField(blank=True, max_length=155, null=True, verbose_name='İletişim')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Adı')),
                ('doc_no', models.CharField(blank=True, max_length=155, null=True, verbose_name='Rehber No')),
                ('phone', models.CharField(max_length=155, verbose_name='Telefon No')),
                ('mail', models.CharField(blank=True, max_length=155, null=True, verbose_name='Mail')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('location', models.ManyToManyField(to='company.city', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('mail', models.CharField(blank=True, max_length=155, null=True, verbose_name='Mail')),
                ('one_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tek Kişilik Ücreti')),
                ('two_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İki Kişilik Ücreti')),
                ('tree_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Üç Kişilik Ücreti')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Fiyat Geçerlilik Tarihi')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.city', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('contact', models.CharField(blank=True, max_length=155, null=True, verbose_name='İletişim')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.city', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='NoVehicleTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=155, verbose_name='Güzergah')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='company.city', verbose_name='Start City')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=155, verbose_name='Güzergah')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('finish_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourfinishcities', to='company.city', verbose_name='Finish City')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourstartcities', to='company.city', verbose_name='Start City')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=155, verbose_name='Güzergah')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('finish_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferfinishcities', to='company.city', verbose_name='Finish City')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferstartcities', to='company.city', verbose_name='Start City')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('browser_info', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employee', verbose_name='Personel')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=155, verbose_name='Araçlar')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasite')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiclecost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.tour', verbose_name='Tour')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.transfer', verbose_name='Transfer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCostPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.vehicle', verbose_name='Araç')),
                ('vehicle_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiclecostprices', to='files.vehiclecost', verbose_name='Vehicle Cost')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Kurulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='Branch')),
                ('location', models.ManyToManyField(to='company.city', verbose_name='Location')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclecost',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.vehiclesupplier', verbose_name='Tedarikçi'),
        ),
    ]
