# Generated by Django 5.1.2 on 2024-11-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='salesprice',
            name='branch',
        ),
    ]
