# Generated by Django 5.1.2 on 2024-11-12 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('operations', '0004_remove_customer_branch_remove_salesprice_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationitemguide',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemguide',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='operationitemguide',
            name='operation_item_novehicle_activity',
        ),
        migrations.RemoveField(
            model_name='operationitemguide',
            name='operation_item_novehicle_tour',
        ),
        migrations.RemoveField(
            model_name='operationitemguide',
            name='operation_item_vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemhotel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemhotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='operationitemhotel',
            name='operation_item_vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemmuseum',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemmuseum',
            name='museums',
        ),
        migrations.RemoveField(
            model_name='operationitemmuseum',
            name='operation_item_novehicle_activity',
        ),
        migrations.RemoveField(
            model_name='operationitemmuseum',
            name='operation_item_novehicle_tour',
        ),
        migrations.RemoveField(
            model_name='operationitemmuseum',
            name='operation_item_vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicleactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicleactivity',
            name='activity_supplier',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicleactivity',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicleactivity',
            name='day',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicleactivity',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationitemotherprice',
            name='operation_item_novehicle_activity',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicleactivityorder',
            name='novehicle_activity',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicleactivityorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicletour',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicletour',
            name='day',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicletour',
            name='novehicletour',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicletour',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationitemotherprice',
            name='operation_item_novehicle_tour',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicletourorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='operationitemnovehicletourorder',
            name='novehicle_tour',
        ),
        migrations.RemoveField(
            model_name='operationitemorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='operationitemorder',
            name='day',
        ),
        migrations.RemoveField(
            model_name='operationitemotherprice',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemotherprice',
            name='operation_item_vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemtour',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemtour',
            name='operation_item_vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemtour',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='operationitemtransfer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemtransfer',
            name='operation_item_vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemtransfer',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicle',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicle',
            name='day',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicle',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicle',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicle',
            name='vehicle_cost',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicle',
            name='vehicle_supplier',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicleorder',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='operationitemvehicleorder',
            name='content_type',
        ),
        migrations.CreateModel(
            name='OperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_items', to='operations.operationday')),
            ],
        ),
        migrations.CreateModel(
            name='OperationSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('sub_item_type', models.CharField(max_length=50)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='OperationItemActivity',
        ),
        migrations.DeleteModel(
            name='OperationItemGuide',
        ),
        migrations.DeleteModel(
            name='OperationItemHotel',
        ),
        migrations.DeleteModel(
            name='OperationItemMuseum',
        ),
        migrations.DeleteModel(
            name='OperationItemNoVehicleActivity',
        ),
        migrations.DeleteModel(
            name='OperationItemNoVehicleActivityOrder',
        ),
        migrations.DeleteModel(
            name='OperationItemNoVehicleTour',
        ),
        migrations.DeleteModel(
            name='OperationItemNoVehicleTourOrder',
        ),
        migrations.DeleteModel(
            name='OperationItemOrder',
        ),
        migrations.DeleteModel(
            name='OperationItemOtherPrice',
        ),
        migrations.DeleteModel(
            name='OperationItemTour',
        ),
        migrations.DeleteModel(
            name='OperationItemTransfer',
        ),
        migrations.DeleteModel(
            name='OperationItemVehicle',
        ),
        migrations.DeleteModel(
            name='OperationItemVehicleOrder',
        ),
    ]
