# Generated by Django 5.1.2 on 2024-11-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_operationitemguide_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsubitem',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='OperationItem',
        ),
        migrations.DeleteModel(
            name='OperationSubItem',
        ),
    ]
