# Generated by Django 5.1.2 on 2024-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_operationitem_operationsubitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
