# Generated by Django 5.1.2 on 2024-11-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_operationitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='operationsubitem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
