# Generated by Django 4.2.4 on 2024-11-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
