# Generated by Django 4.2.4 on 2024-11-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdetail_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetail',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
